Keep virtualenv below 20.0.0
We have problems with shellinabox' mitmproxy in a newly-built container.
We assume it's because of the virtualenv version jump, with which we had
problems earlier. The problem manifests as
   IOError: [Errno 2] No such file or directory: '/usr/pyvenv.cfg'